debug: true

mysql:
  host: localhost
  port: 3306
  database: minecraft
  user: root
  password: password

place-boss-cooldown: 2

mundos-bloqueados:
  - "world1"
  - "world2"
  - "world3"

boss-per-player: 20

# Aqui, todas as mensagens suportam tanto uma linha de mensagem ou uma lista de mensagens
messages:
  no-permission: "&cVocê não tem permissão para isso!"
  player-not-found: "&cJogador não encontrado: {NAME}"
  boss-not-found: "&cBoss não encontrado: {NAME}"
  matadora-not-found: "&cMatadora não encontrada: {NAME}"
  cant-place: "&cVocê pode colocar o boss apenas na sua plot ou em plots que você tem permissão!"
  receive-boss: "&aVocê recebeu {AMOUNT}x do boss {BOSS-NAME}"
  receive-matadora: "&aVocê recebeu a matadora {MATADORA-NAME}"
  only-matadora: "&cEsse boss recebe dano apenas de Matadoras!"
  cooldown-message: "&cAguarde mais {SECONDS}s para fazer isso!"
  boss-no-have-awards: "&cEsse boss não tem nenhuma recompensa!"
  reward-menu:
    title: "Recompensas de {BOSS-NAME}"
    lore-added:
      - " "
      - "&7Chance: {CHANCE}%"